project:
  type: website

website:
  page-navigation: true
  title: "CSC2626 - Fall 2024"
  description: "Homepage for CSC2626 - Imitation Learning for Robotics, Fall 2024."
  site-url: "https://csc2626.github.io/website/"

  repo-url: https://github.com/csc2626/website
  repo-actions: [edit, issue]

  open-graph: true

  twitter-card:
    creator: "@minebocek"
    image: "images/twitter-card.png"

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Florian Shkurti"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/DrawingHands.jpg"
    pinned: true
    align: center
    title: "CSC2626 Imitation Learning for Robotics"
    
    tools:
      - icon: github
        href: https://github.com/csc2626
        text: "Github workspace for the course"
      - icon: chat-quote
        href: https://piazza.com/utoronto.ca/fall2024/csc2626/home
        text: "Discuss on Piazza"
      - icon: megaphone
        href: https://q.utoronto.ca/courses/354032
        text: "Official announcements on Quercus"
      - icon: envelope-at
        href: course-team.html
        text: "Email teaching staff"
      - icon: robot
        href: https://robotics.utoronto.ca/
        text: "UofT Robotics Institute"
   	
        
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Overview
      - href: https://piazza.com/utoronto.ca/fall2024/csc2626/home
        text: Piazza
      - href: https://q.utoronto.ca/courses/354032
        text: Quercus	
      - href: course-grading.qmd
        text: Grading
      - href: course-team.qmd
        text: Teaching Staff
      - href: course-schedule.qmd
        text: Schedule
      - href: course-links.qmd
        text: Robotics Simulators
      - href: project-description.qmd
        text: Final Project
      
format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    
freeze: auto

editor: visual